name:                openai-hs
version:             0.3.0.1
github:              "agrafix/openai-hs"
license:             BSD3
author:              "Alexander Thiemann <mail@thiemann.at>"
maintainer:          "Alexander Thiemann <mail@thiemann.at>"
copyright:           "2021-2023 Alexander Thiemann <mail@thiemann.at>"

extra-source-files:
  - README.md

synopsis:            Unofficial OpenAI client
category:            Web

description:         Unofficial OpenAI client

dependencies:
  - base >= 4.7 && < 5
  - openai-servant >= 0.2.1  
  - aeson
  - casing
  - text
  - servant
  - servant-auth-client
  - servant-client
  - servant-multipart-client
  - http-client
  - bytestring
  - cpphs
  - http-types

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-record-updates

default-extensions:
  - OverloadedStrings
  - DataKinds
  - TypeOperators
  - TypeFamilies
  - GADTs
  - FlexibleInstances
  - FlexibleContexts
  - MultiParamTypeClasses
  - StrictData
  - ScopedTypeVariables
  - DeriveGeneric
  - DeriveFunctor

library:
  source-dirs: src

tests:
  openai-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - openai-hs
      - hspec
      - http-client-tls
      - vector
      - bytestring
      - containers
      - servant-client-core
